### PR TITLE
fix type hint using pymongo client session instead of motor client session

### PR DESCRIPTION
**Pull request by CAPITAINMARVEL**
this pull request  fix the type hint of session

### CODE REVIEW

**Review by Riverfount — DISMISSED** [review]
LGTM

**Review by 07pepa — DISMISSED** [review]

**Review by Riverfount — APPROVED** [review]
LGTM

**Review by Riverfount — APPROVED** [review]
I think it is ok!

**Review by LawMixer — APPROVED** [review]

**Review by staticxterm — APPROVED** [review]
Looks good. The only potential problem may be when syncing Bunnet with latest Beanie, but I'm not sure how that is done exactly. From the perspective of Beanie alone, this is not a breaking change. Thank you.

**Pull request merged**
