### PR TITLE
Removed calls to function causing deprecation warning where possible

### PR DESCRIPTION
**Pull request by 07pepa**
i removed most deprecated warning only left is hiden=True

I also removed some unreachable code

### CODE REVIEW

**Comment by roman-right** [comment]
Hi @07pepa ,
Could you please check the tests. And there are some conflicts.
Thank you for the PR!

**Comment by 07pepa** [comment]
is all green https://github.com/07pepa/beanie/actions/runs/8921580966/job/24501959415

**Comment by 07pepa** [comment]
@roman-right ?

**Review by roman-right — APPROVED** [review]
Looks good

**Comment by 07pepa** [comment]
running ci cd maybe

and @roman-right merging it

**Comment by 07pepa** [comment]
@dotKokott can be merge RN

**Review by LawMixer — APPROVED** [review]
Looks good to me

**Review by adeelsohailahmed — APPROVED** [review]

**Pull request merged**
