### PR TITLE
expose ExpressionField, use __slots__ for several class

### PR DESCRIPTION
**Pull request by CAPITAINMARVEL**

### CODE REVIEW

**Review by Riverfount — APPROVED** [review]
Great Job

**Comment by Riverfount** [comment]
> > Great Job. But the GA is not ok, just fix it and it is ok to me.
> 
> GA ?

Github Action lol

**Comment by staticxterm** [comment]
I'm sorry, but I still don't get what issue this is trying to solve... Are there any usage examples or benchmarks where this is proven to be faster than it currently is?

**Review by Riverfount — APPROVED** [review]
Great!

**Pull request closed without merging**
