### PR TITLE
Extend motor option to beanie

### PR DESCRIPTION
**Pull request by Dudesons**
Add the possibility to install optional packages from motor.
As an example using the the aws option allow to connect with an IAM role.

### CODE REVIEW

**Review by 07pepa — DISMISSED** [review]

**Comment by Dudesons** [comment]
Any chance to have more reviews or other reviewers @07pepa ? or should I go to discord in order to discuss about this PR ?

**Comment by 07pepa** [comment]
@Dudesons  well i asked on discord and you are welcomed on discord

but i requested usual active reviewers already...

**Review by adeelsohailahmed — COMMENTED** [review]
Thank you for your contribution. Could you update the documentation on how to utilize this, please?

**Comment by Dudesons** [comment]
@adeelsohailahmed  ok, I just added it in the `getting_started` but not sure if it's the best place or should I put it in the `README` or both

**Comment by adeelsohailahmed** [comment]
> @adeelsohailahmed ok, I just added it in the `getting_started` but not sure if it's the best place or should I put it in the `README` or both

Thank you for adding the documentation.

`getting_started` seems right to me. Might not be a bad idea to include a condensed version in the README too. For condensed version, we could mention the supported dependencies, and provide an example or two.

**Comment by Dudesons** [comment]
> Thank you for adding the documentation.
> 
> > @adeelsohailahmed ok, I just added it in the `getting_started` but not sure if it's the best place or should I put it in the `README` or both
> 
> `getting_started` seems right to me. Might not be a bad idea to include a condensed version in the README too. For condensed version, we could mention the supported dependencies, and provide an example or two.

I added the reference from README to getting started

**Review by adeelsohailahmed — APPROVED** [review]
Looks good to me. Thank you.

**Review by Riverfount — APPROVED** [review]
LGTM

**Review by 07pepa — APPROVED** [review]

**Pull request merged**
