### PR TITLE
feat(skip_index): possibility added to skip index actions

### PR DESCRIPTION
**Pull request by jorma16**
Just added the possibility to avoid index operations in init, like someone ask here: https://github.com/BeanieODM/beanie/discussions/924

And other people workaround here: https://github.com/BeanieODM/beanie/discussions/608

Please, take care of this, I really need this and I think that is very interesting for read only applications.

### CODE REVIEW

**Comment by roman-right** [comment]
Hi @jorma16 ,
Thank you very much for the PR. THis feature is so reasonable. Could you please add a test for it? It could check if indexes were not created in the db.

**Comment by jorma16** [comment]
Hi! I couldn't check this PR until today, sorry for the delay.

I have added the tests that you requested, thanks in advance!

**Review by adeelsohailahmed — APPROVED** [review]
Thank you for your contribution!

**Review by staticxterm — APPROVED** [review]

**Review by Riverfount — APPROVED** [review]
It's ok for me.

**Pull request merged**
