### PR TITLE
Add test to ensure dict with enum keys are encoded properly

### PR DESCRIPTION
**Pull request by adeelsohailahmed**
The issue raised in #829 seems to have been fixed in PR #868 

https://github.com/BeanieODM/beanie/blob/0b8d50ba1fff44d7b92d726a1376619cacb4c5fd/beanie/odm/utils/encoder.py#L134-L138

Only the relevant test was missing to ensure the regression was adequately addressed. This PR adds that test.

### CODE REVIEW

**Review by 07pepa — DISMISSED** [review]

**Review by Riverfount — DISMISSED** [review]
I think that a good work

**Review by 07pepa — APPROVED** [review]

**Review by Riverfount — APPROVED** [review]
LGTM

**Comment by 07pepa** [comment]
raised as issue to pydantic

**Comment by adeelsohailahmed** [comment]
It's good that you're raising this issue in Pydantic, @07pepa. I appreciate that.

This PR, however, is not adding any specific encoding logic to overcome what may be possible Pydantic limitations. It's only adding a test to confirm that the existing Beanie behaviour that had regressed in between 1.23.6 -> 1.24.0 has been fixed.

**Comment by pepe-rtmlab** [comment]
actualy this is mistage

**Comment by 07pepa** [comment]
actualy this is mistage

**Review by 07pepa — APPROVED** [review]

**Comment by 07pepa** [comment]
@adeelsohailahmed  resolve conficts please

**Comment by adeelsohailahmed** [comment]
> @adeelsohailahmed resolve conficts please

I don't see any conflicts.

**Comment by adeelsohailahmed** [comment]
Thank you for the reviews

**Pull request merged**
