### PR TITLE
Fix typo in source code comment in inheritance.md

### PR DESCRIPTION
**Pull request by fnogatz**
Typo can be seen online at https://beanie-odm.dev/tutorial/inheritance/:

image

----

*The work on this PR was sponsored by [SUSI&James GmbH](https://susiandjames.com/).*

### CODE REVIEW

**Comment by 07pepa** [comment]
hm this could help https://github.com/crate-ci/typos as well maybe you can add it as precomit?

**Review by LawMixer — APPROVED** [review]
Seems like a non-breaking change to me, appreciate you making a pull request!

**Comment by fnogatz** [comment]
So all it takes to get merged is two additional approvers? 😄

**Review by adeelsohailahmed — APPROVED** [review]
Thank you

**Review by LawMixer — APPROVED** [review]

**Pull request merged**
