### PR TITLE
Handle limit and session in .count() method

### PR DESCRIPTION
**Pull request by CAPITAINMARVEL**
This PR is to fix the issue related to the count method

- Fixes https://github.com/BeanieODM/beanie/issues/1010
- Fixes https://github.com/BeanieODM/beanie/issues/848

### CODE REVIEW

**Review by LawMixer — APPROVED** [review]
simple pr, looks good!

**Comment by adeelsohailahmed** [comment]
Closes #1010 & #848

**Review by adeelsohailahmed — APPROVED** [review]
LGTM

**Review by 07pepa — APPROVED** [review]

**Comment by 07pepa** [comment]
this is marvelous work... pun intended

**Comment by martincpt** [comment]
I just realised that this PR broke our CRUD app.

I don't think this functionality is quite right as it is, because it's breaking any implementation - especially pagination - that relies on the real count number.

Don't you think it should be optional instead?

**Pull request merged**
