### PR TITLE
Make BsonBinary be serializable by fastapi in json even data is utf-8…

### PR DESCRIPTION
**Pull request by 07pepa**
… unsafe

### CODE REVIEW

**Comment by 07pepa** [comment]
Fixes bug where BsonBinary could not be serialized by fastapi directly

**Review by LawMixer — APPROVED** [review]
Looks good to me!

**Review by LawMixer — DISMISSED** [review]

**Review by Riverfount — APPROVED** [review]

**Review by Riverfount — APPROVED** [review]
LGTM

**Comment by 07pepa** [comment]
i raised this as issue in pydantic

**Pull request closed without merging**
