### PR TITLE
fix: example of find by id and link to finding-documents

### PR DESCRIPTION
**Pull request by fredowashere**

### CODE REVIEW

**Comment by dsevilla** [comment]
This seems to be applied already, but not acted upon the pull request.

**Comment by fredowashere** [comment]
@dsevilla I guess it won't be merged right?

**Comment by dsevilla** [comment]
I honestly don't know. I was just trying to assess the possibility of fixing issue #885, and looked to the pending PRs to see if anybody gave it a try.

They seem to be transitioning to a group-based effort, so it may take some time to answer pending issues or PRs.

In any case, this one in particular seems to be fixed already.

**Review by 07pepa — APPROVED** [review]

**Comment by fredowashere** [comment]
@07pepa thanks! Waiting for other approvals

**Review by adeelsohailahmed — APPROVED** [review]

**Comment by fredowashere** [comment]
Thanks @adeelsohailahmed

**Review by Riverfount — APPROVED** [review]

**Comment by mg3146** [comment]
Hi - did this end up getting fixed?  Passing original_field to Field() is still causing a pydantic warning, and its unclear if passing it via json_schema_extra = {original_field : xxx} is supported.

**Pull request merged**
